name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # أضف هذا الجزء ليقوم GitHub بالعمل داخل مجلد ps4icon
    defaults:
      run:
        working-directory: ./ps4icon 

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        # تأكد من تحديث المسار هنا أيضاً ليشمل المجلد الفرعي
        path: ps4icon/build/app/outputs/flutter-apk/app-release.apk
