name: Android Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # البحث عن gradlew في أي مكان ومنحه صلاحية التنفيذ
    - name: Grant execute permission for gradlew
      run: |
        chmod +x $(find . -name "gradlew")

    # بناء التطبيق باستخدام الملف الذي تم العثور عليه
    - name: Build with Gradle
      run: |
        ./$(find . -name "gradlew") assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: "**/app-debug.apk"
